To get started with GORM for Cassandra you need configure it as a dependency in `build.gradle`:

[source,groovy]
----
dependencies {
    compile 'org.grails.plugins:cassandra:VERSION'
}
----


The next step is to setup a running Cassandra server. 
Refer to the http://cassandra.apache.org/doc/latest/getting_started/index.html[Apache Cassandra Getting Started Guide] for an explanation on how to setup and startup a Cassandra instance.
Once installed, starting Cassandra is typically a matter of executing the following command:

[source,groovy]
----
CASSANDRA_HOME/bin/cassandra -f
----

With the above command executed in a terminal window you should see output like the following appear:

[source,groovy]
----
INFO 00:11:16,935 Starting listening for CQL clients on localhost/127.0.0.1:9042...
INFO 00:11:17,013 Using TFramedTransport with a max frame size of 15728640 bytes.
INFO 00:11:17,014 Binding thrift service to localhost/127.0.0.1:9160
INFO 00:11:17,042 Using synchronous/threadpool thrift server on localhost : 9160
INFO 00:11:17,042 Listening for thrift clients...
----

As you can see the server listens for CQL clients on port 9042, but don't worry the Cassandra plugin for Grails will automatically configure itself to look for Cassandra on that port by default.

If you want to configure how Grails connects to Cassandra then you can do so using the following settings in `grails-app/conf/application.yml`:

[source,groovy]
----
grails:
    cassandra:
        contactPoints: localhost
        port: 9042
        keyspace:
            name: foo
    }
}
----

WARNING: Spring Boot 1.4.x and above includes http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-nosql.html#boot-features-cassandra[Cassandra Auto Configuration] and by default in Grails 3.2.x above you will need to configure Cassandra using the appropriate Spring Boot configuration unless you exclude the auto configuration in your `Application` class. For example:

[source,groovy]
----
import org.springframework.boot.autoconfigure.cassandra.*
import org.springframework.boot.autoconfigure.data.cassandra.*
import grails.boot.GrailsApp
import grails.boot.config.GrailsAutoConfiguration
import org.springframework.boot.autoconfigure.EnableAutoConfiguration

@EnableAutoConfiguration(exclude=[CassandraAutoConfiguration, CassandraDataAutoConfiguration])
class Application extends GrailsAutoConfiguration {
    static void main(String[] args) {
        GrailsApp.run(Application, args)
    }
}
----